### ISSUE TITLE
Tests will fail in 1.82 due to an old soundness hole in hashbrown

### ISSUE THREAD

**Issue by saethlin** [jonhoo/griddle#21]
I am filing this issue because this project's tests failed in the crater runs for Rust 1.82: https://github.com/rust-lang/rust/issues/130579, you can reproduce this failure with cargo +beta test or cargo +nightly test.

griddle uses a version of hashbrown that doesn't have this patch https://github.com/rust-lang/hashbrown/pull/268 so the cause of the UB that's now detected is actually in hashbrown. But this crate's test suite will start to fail, so this is where I'm posting the heads-up issue.

**Comment by jonhoo** [comment]
Thanks for the heads up! This is now fixed in 0.6.0.
