### ISSUE TITLE
Avoid hacky workaround for with_capacity

### ISSUE THREAD

**Issue by jonhoo** [jonhoo/griddle#5]
When we have to allocate a new table, we want to continue with factor-of-two resizing when possible. Unfortunately, `hashbrown::RawTable::with_capacity` (I think) allocates more or less the capacity we give it, rather than rounding up. So, we resort to this workaround:
https://github.com/jonhoo/griddle/blob/c68eb4c7f8a4a305f1e57b893479f8a7fe22e5b9/src/lib.rs#L746-L749

It'd be nice to get rid of that. Benchmarks may tell us that `with_capacity` works just fine..

**Comment by Amanieu** [comment]
`reserve` and `with_capacity` are equivalent: they both take the capacity (number of elements you can insert before resizing) as an argument, not the number of buckets.

**Comment by Amanieu** [comment]
They also both round up to the next power of two.

**Comment by jonhoo** [comment]
Hmm, I could be wrong, but that doesn't quite seem like the case from the code? While `reserve` does eventually call `try_with_capacity`, it computes the additional capacity to request using a `usize::max` [here](https://github.com/rust-lang/hashbrown/blob/efbd03661fc9df0e594ecc89784107353cc71060/src/raw/mod.rs#L702), which seems to do some rounding up. Is that logic not relevant/important?

**Comment by Amanieu** [comment]
`new_items` may be less than `full_capacity` at this point if the rehash path was reached because all of our free space is used up by tombstones. The `usize::max` here is to force us to use the next size in that case.
